### ISSUE TITLE
Unrecognized user type: offline

### ISSUE THREAD

**Issue by fluentpwn** [fn2006/PollyMC#12]
### Operating System

Linux

### Version of PollyMC

Latest self-built on x86_64 with musl libc, OpenJDK 17 and cmake 3.22.2 according to guide linked in `BUILD.md`

### Description of bug

When trying to run latest available vanilla with offline account, this occurs:
```
[13:26:44] [main/INFO]: Building optimized datafixer
[13:26:46] [main/WARN]: Unrecognized user type: offline
[13:26:47] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[13:26:48] [Render thread/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-3.5.41.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:140) ~[authlib-3.5.41.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:47) ~[authlib-3.5.41.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:158) ~[authlib-3.5.41.jar:?]
	at eev.a(SourceFile:677) [minecraft-1.19-client.jar:?]
	at eev.<init>(SourceFile:415) [minecraft-1.19-client.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:198) [minecraft-1.19-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:85) ~[authlib-3.5.41.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48) ~[authlib-3.5.41.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:121) ~[authlib-3.5.41.jar:?]
	... 14 more
[13:26:48] [Render thread/INFO]: Setting user: c4x
[13:26:49] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 build 7
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00000000000239a6, pid=15572, tid=15573
#
# JRE version: OpenJDK Runtime Environment (17.0.3+7) (build 17.0.3+7-void-r3)
# Java VM: OpenJDK 64-Bit Server VM (17.0.3+7-void-r3, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  0x00000000000239a6
#
```

### Steps to reproduce

- Create an offline account
- Run vanilla Minecraft with it

### Suspected cause

I suspect that it's due to the warning preceding to the error: account isn't interpreted as offline one and requests are sent anyway

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by fn2006** [comment]
See https://github.com/PolyMC/PolyMC/issues/779, Mojang's provided liblwjgl.so is built against glibc and doesn't work with musl, you need to compile GLFW yourself and enable the "Use system installation of GLFW" option, I've never used Void though so I not entirely sure how you'd go about doing that.

The authlib error doesn't crash the game and just means you can't play on Realms or Online-mode servers.

**Comment by fluentpwn** [comment]
> See [PolyMC#779](https://github.com/PolyMC/PolyMC/issues/779), Mojang's provided liblwjgl.so is built against glibc and doesn't work with musl, you need to compile GLFW yourself and enable the "Use system installation of GLFW" option, I've never used Void though so I not entirely sure how you'd go about doing that.
> 
> The authlib error doesn't crash the game and just means you can't play on Realms or Online-mode servers.

Thanks for fast response!
Followed the steps. now the error is different:
```
Jul 27, 2022 2:08:45 PM org.polymc.EntryPoint listen
SEVERE: Exception caught from launcher.
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
	at ac.a(SourceFile:65)
	at eev.a(SourceFile:2306)
	at eev.a(SourceFile:2301)
	at net.minecraft.client.main.Main.main(SourceFile:207)
	... 9 more

Jul 27, 2022 2:08:45 PM org.polymc.EntryPoint main
```

**Comment by fn2006** [comment]
Sorry I took a while to get back to you, I didn't expect you to respond so fast lol.

I think the instructions I gave you were wrong, I told you to compile and install GLFW but I think you also need to compile and install LWJGL, sorry.

**Comment by fluentpwn** [comment]
> Sorry I took a while to get back to you, I didn't expect you to respond so fast lol.
> 
> I think the instructions I gave you were wrong, I told you to compile and install GLFW but I think you also need to compile and install LWJGL, sorry.

Can't compile LWJGL currently, so will close the issue for now.
