### ISSUE TITLE
Game crashes with offline account

### ISSUE THREAD

**Issue by squeaktoy** [fn2006/PollyMC#138]
### Operating System

Gentoo

### Version of PollyMC

PollyMC 8.0

### Version of Qt

Qt 5.15.11

### Description of bug

```
PollyMC version: 8.0 (Gentoo)


Launched instance in online mode

authserver.mojang.com resolves to:
    [18.239.69.26, 18.239.69.66, 18.239.69.110, 18.239.69.67]

session.minecraft.net resolves to:
    [2620:1ec:bdf::67, 2620:1ec:46::67, 13.107.253.67, 13.107.226.67]

textures.minecraft.net resolves to:
    [2620:1ec:48:1::67, 2620:1ec:29:1::67, 13.107.226.67, 13.107.253.67]

api.mojang.com resolves to:
    [2620:1ec:46::44, 2620:1ec:bdf::44, 13.107.226.67, 13.107.253.67]


Minecraft folder is:
/media/tank/games/PolyMC/instances/1.20.4 Fabric/.minecraft


Java path is:
/usr/bin/java


Java is version 17.0.8.1, using 64 (amd64) architecture, from Gentoo.


Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
NVIDIA Corporation GM107 [GeForce GTX 750] (rev a2)

Subsystem: Micro-Star International Co., Ltd. [MSI] GM107 [GeForce GTX 750]

Kernel driver in use: nvidia

OpenGL version string: 4.6.0 NVIDIA 535.146.02

Main Class:
  net.minecraft.client.main.Main

Native path:
  /media/tank/games/PolyMC/instances/1.20.4 Fabric/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Using system OpenAL.
Using system GLFW.

Libraries:
  /home/user/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw-natives-linux/3.3.2/lwjgl-glfw-natives-linux-3.3.2.jar
  /home/user/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2.jar
  /home/user/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc-natives-linux/3.3.2/lwjgl-jemalloc-natives-linux-3.3.2.jar
  /home/user/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2.jar
  /home/user/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-natives-linux/3.3.2/lwjgl-natives-linux-3.3.2.jar
  /home/user/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-openal-natives-linux/3.3.2/lwjgl-openal-natives-linux-3.3.2.jar
  /home/user/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2.jar
  /home/user/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl-natives-linux/3.3.2/lwjgl-opengl-natives-linux-3.3.2.jar
  /home/user/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2.jar
  /home/user/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-stb-natives-linux/3.3.2/lwjgl-stb-natives-linux-3.3.2.jar
  /home/user/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2.jar
  /home/user/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd-natives-linux/3.3.2/lwjgl-tinyfd-natives-linux-3.3.2.jar
  /home/user/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2.jar
  /home/user/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2.jar
  /home/user/.local/share/PrismLauncher/libraries/com/github/oshi/oshi-core/6.4.5/oshi-core-6.4.5.jar
  /home/user/.local/share/PrismLauncher/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar
  /home/user/.local/share/PrismLauncher/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /home/user/.local/share/PrismLauncher/libraries/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar
  /home/user/.local/share/PrismLauncher/libraries/com/ibm/icu/icu4j/73.2/icu4j-73.2.jar
  /home/user/.local/share/PrismLauncher/libraries/com/mojang/authlib/6.0.52/authlib-6.0.52.jar
  /home/user/.local/share/PrismLauncher/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  /home/user/.local/share/PrismLauncher/libraries/com/mojang/brigadier/1.2.9/brigadier-1.2.9.jar
  /home/user/.local/share/PrismLauncher/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar
  /home/user/.local/share/PrismLauncher/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
  /home/user/.local/share/PrismLauncher/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  /home/user/.local/share/PrismLauncher/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  /home/user/.local/share/PrismLauncher/libraries/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar
  /home/user/.local/share/PrismLauncher/libraries/commons-io/commons-io/2.13.0/commons-io-2.13.0.jar
  /home/user/.local/share/PrismLauncher/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /home/user/.local/share/PrismLauncher/libraries/io/netty/netty-buffer/4.1.97.Final/netty-buffer-4.1.97.Final.jar
  /home/user/.local/share/PrismLauncher/libraries/io/netty/netty-codec/4.1.97.Final/netty-codec-4.1.97.Final.jar
  /home/user/.local/share/PrismLauncher/libraries/io/netty/netty-common/4.1.97.Final/netty-common-4.1.97.Final.jar
  /home/user/.local/share/PrismLauncher/libraries/io/netty/netty-handler/4.1.97.Final/netty-handler-4.1.97.Final.jar
  /home/user/.local/share/PrismLauncher/libraries/io/netty/netty-resolver/4.1.97.Final/netty-resolver-4.1.97.Final.jar
  /home/user/.local/share/PrismLauncher/libraries/io/netty/netty-transport-classes-epoll/4.1.97.Final/netty-transport-classes-epoll-4.1.97.Final.jar
  /home/user/.local/share/PrismLauncher/libraries/io/netty/netty-transport-native-epoll/4.1.97.Final/netty-transport-native-epoll-4.1.97.Final-linux-aarch_64.jar
  /home/user/.local/share/PrismLauncher/libraries/io/netty/netty-transport-native-epoll/4.1.97.Final/netty-transport-native-epoll-4.1.97.Final-linux-x86_64.jar
  /home/user/.local/share/PrismLauncher/libraries/io/netty/netty-transport-native-unix-common/4.1.97.Final/netty-transport-native-unix-common-4.1.97.Final.jar
  /home/user/.local/share/PrismLauncher/libraries/io/netty/netty-transport/4.1.97.Final/netty-transport-4.1.97.Final.jar
  /home/user/.local/share/PrismLauncher/libraries/it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar
  /home/user/.local/share/PrismLauncher/libraries/net/java/dev/jna/jna-platform/5.13.0/jna-platform-5.13.0.jar
  /home/user/.local/share/PrismLauncher/libraries/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar
  /home/user/.local/share/PrismLauncher/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /home/user/.local/share/PrismLauncher/libraries/org/apache/commons/commons-compress/1.22/commons-compress-1.22.jar
  /home/user/.local/share/PrismLauncher/libraries/org/apache/commons/commons-lang3/3.13.0/commons-lang3-3.13.0.jar
  /home/user/.local/share/PrismLauncher/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /home/user/.local/share/PrismLauncher/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar
  /home/user/.local/share/PrismLauncher/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
  /home/user/.local/share/PrismLauncher/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
  /home/user/.local/share/PrismLauncher/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
  /home/user/.local/share/PrismLauncher/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  /home/user/.local/share/PrismLauncher/libraries/org/slf4j/slf4j-api/2.0.7/slf4j-api-2.0.7.jar
  /home/user/.local/share/PrismLauncher/libraries/com/mojang/minecraft/1.20.4/minecraft-1.20.4-client.jar

Native libraries:

Params:
  --username  --version 1.20.4 --gameDir /media/tank/games/PolyMC/instances/1.20.4 Fabric/.minecraft --assetsDir /home/user/.local/share/PrismLauncher/assets --assetIndex 12 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Launcher: standard

Java Arguments:
[-Dorg.lwjgl.openal.libname=/usr/lib64/libopenal.so, -Dorg.lwjgl.glfw.libname=/usr/lib64/libglfw.so, -Xms2048m, -Xmx4096m, -Duser.language=en]


Minecraft process ID: 19148


[18:37:50] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 222 milliseconds
[18:37:51] [main/WARN]: Unrecognized user type: offline
[18:37:52] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[18:37:52] [Render thread/INFO]: Setting user: BoingBoing
[18:37:52] [Render thread/INFO]: Backend library: LWJGL version 3.3.2+13
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2024-01-15 18:37:52
Description: Initializing game

java.lang.ExceptionInInitializerError
	at org.lwjgl.glfw.GLFW.nglfwGetError(GLFW.java:1251)
	at org.lwjgl.glfw.GLFW.glfwGetError(GLFW.java:1280)
	at epf.a(SourceFile:136)
	at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:66)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:848)
	at evi.<init>(SourceFile:512)
	at net.minecraft.client.main.Main.main(SourceFile:223)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.NullPointerException: A required function is missing: glfwInitAllocator
	at org.lwjgl.system.APIUtil.requiredFunctionMissing(APIUtil.java:145)
	at org.lwjgl.system.APIUtil.apiGetFunctionAddress(APIUtil.java:139)
	at org.lwjgl.glfw.GLFW$Functions.<clinit>(GLFW.java:42)
	... 10 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.lwjgl.glfw.GLFW.nglfwGetError(GLFW.java:1251)
	at org.lwjgl.glfw.GLFW.glfwGetError(GLFW.java:1280)
	at epf.a(SourceFile:136)
	at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:66)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:848)
	at evi.<init>(SourceFile:512)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:223)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Linux (amd64) version 6.1.67-gentoo
	Java Version: 17.0.8.1, Gentoo
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Gentoo
	Memory: 1876122112 bytes (1789 MiB) / 2147483648 bytes (2048 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: GM107 [GeForce GTX 750]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288.00
	Graphics card #0 deviceId: 0x1381
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 44750.84
	Virtual memory used (MB): 26841.80
	Swap memory total (MB): 32766.99
	Swap memory used (MB): 8283.51
	JVM Flags: 2 total; -Xms2048m -Xmx4096m
	Launched Version: 1.20.4
	Launcher name: PollyMC
	Backend library: LWJGL version 3.3.2+13
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Universe: 404
	Type: Client (map_client.txt)
	Locale: en_US
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /media/tank/games/PolyMC/instances/1.20.4 Fabric/.minecraft/crash-reports/crash-2024-01-15_18.37.52-client.txt
Process exited with code 255.
```

### Steps to reproduce

1. Add offline user
2. Create instance (1.20.4, vanilla or any mod loader)
3. Launch the game

### Suspected cause

Microsoft is discriminating against me. I have bought a legal copy of this game back in 2011, but never migrated to Microsoft account. Let me play the game I have a right to.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by squeaktoy** [comment]
Or something might be going wrong with glfw. I thought the unknown account type warning was causing the crash, but the back trace is hard to read.

**Comment by squeaktoy** [comment]
I found the fix: disable `Settings -> Minecraft -> Tweaks -> Use system installation of GLFW`
