### ISSUE TITLE
Minecraft fails to launch with Forge

### ISSUE THREAD

**Issue by Hambed1** [fn2006/PollyMC#145]
### Operating System

Windows

### Version of PollyMC

PollyMC 8.0

### Version of Qt

Qt version 6.6.0

### Description of bug

Minecraft instance 1.20.1 should launch with Forge installed (vanilla instance works fine), instead it shows this error:

PollyMC version: 8.0 (official)

Launched instance in online mode

authserver.mojang.com resolves to:
    [18.161.97.35, 18.161.97.65, 18.161.97.6, 18.161.97.46]

session.minecraft.net resolves to:
    [13.107.246.43, 13.107.213.43]

textures.minecraft.net resolves to:
    [13.107.213.43, 13.107.246.43]

api.mojang.com resolves to:
    [13.107.213.43, 13.107.246.43]

Minecraft folder is:
C:/Users/Hamb/AppData/Roaming/PollyMC/instances/Huminar/.minecraft

Java path is:
C:/Program Files/Eclipse Adoptium/jdk-17.0.10.7-hotspot/bin/javaw.exe

Checking Java version...
Java is version 17.0.10, using 64 (amd64) architecture, from Eclipse Adoptium.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Users/Hamb/AppData/Roaming/PollyMC/instances/Huminar/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-glfw-natives-windows-arm64/3.3.1/lwjgl-glfw-natives-windows-arm64-3.3.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-glfw-natives-windows-x86/3.3.1/lwjgl-glfw-natives-windows-x86-3.3.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-glfw-natives-windows/3.3.1/lwjgl-glfw-natives-windows-3.3.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows-arm64/3.3.1/lwjgl-jemalloc-natives-windows-arm64-3.3.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows-x86/3.3.1/lwjgl-jemalloc-natives-windows-x86-3.3.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows/3.3.1/lwjgl-jemalloc-natives-windows-3.3.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-natives-windows-arm64/3.3.1/lwjgl-natives-windows-arm64-3.3.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-natives-windows-x86/3.3.1/lwjgl-natives-windows-x86-3.3.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-natives-windows/3.3.1/lwjgl-natives-windows-3.3.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-openal-natives-windows-arm64/3.3.1/lwjgl-openal-natives-windows-arm64-3.3.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-openal-natives-windows-x86/3.3.1/lwjgl-openal-natives-windows-x86-3.3.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-openal-natives-windows/3.3.1/lwjgl-openal-natives-windows-3.3.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-opengl-natives-windows-arm64/3.3.1/lwjgl-opengl-natives-windows-arm64-3.3.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-opengl-natives-windows-x86/3.3.1/lwjgl-opengl-natives-windows-x86-3.3.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-opengl-natives-windows/3.3.1/lwjgl-opengl-natives-windows-3.3.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-stb-natives-windows-arm64/3.3.1/lwjgl-stb-natives-windows-arm64-3.3.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-stb-natives-windows-x86/3.3.1/lwjgl-stb-natives-windows-x86-3.3.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-stb-natives-windows/3.3.1/lwjgl-stb-natives-windows-3.3.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows-arm64/3.3.1/lwjgl-tinyfd-natives-windows-arm64-3.3.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows-x86/3.3.1/lwjgl-tinyfd-natives-windows-x86-3.3.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows/3.3.1/lwjgl-tinyfd-natives-windows-3.3.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/com/google/code/gson/gson/2.10/gson-2.10.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/com/ibm/icu/icu4j/71.1/icu4j-71.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/com/mojang/authlib/4.0.43/authlib-4.0.43.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/com/mojang/brigadier/1.1.8/brigadier-1.1.8.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/io/netty/netty-buffer/4.1.82.Final/netty-buffer-4.1.82.Final.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/io/netty/netty-codec/4.1.82.Final/netty-codec-4.1.82.Final.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/io/netty/netty-common/4.1.82.Final/netty-common-4.1.82.Final.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/io/netty/netty-handler/4.1.82.Final/netty-handler-4.1.82.Final.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/io/netty/netty-resolver/4.1.82.Final/netty-resolver-4.1.82.Final.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/io/netty/netty-transport-classes-epoll/4.1.82.Final/netty-transport-classes-epoll-4.1.82.Final.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/io/netty/netty-transport-native-unix-common/4.1.82.Final/netty-transport-native-unix-common-4.1.82.Final.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/io/netty/netty-transport/4.1.82.Final/netty-transport-4.1.82.Final.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/it/unimi/dsi/fastutil/8.5.9/fastutil-8.5.9.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/net/java/dev/jna/jna-platform/5.12.1/jna-platform-5.12.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/net/java/dev/jna/jna/5.12.1/jna-5.12.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/slf4j/slf4j-api/2.0.1/slf4j-api-2.0.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/io/github/zekerzhayard/ForgeWrapper/1.5.8-prism/ForgeWrapper-1.5.8-prism.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/cpw/mods/securejarhandler/2.1.10/securejarhandler-2.1.10.jar (missing)
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/ow2/asm/asm/9.5/asm-9.5.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/ow2/asm/asm-commons/9.5/asm-commons-9.5.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/ow2/asm/asm-tree/9.5/asm-tree-9.5.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/ow2/asm/asm-util/9.5/asm-util-9.5.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/ow2/asm/asm-analysis/9.5/asm-analysis-9.5.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/net/minecraftforge/accesstransformers/8.0.4/accesstransformers-8.0.4.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/net/minecraftforge/eventbus/6.0.5/eventbus-6.0.5.jar (missing)
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/net/minecraftforge/forgespi/7.0.1/forgespi-7.0.1.jar (missing)
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/net/minecraftforge/coremods/5.0.1/coremods-5.0.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/cpw/mods/modlauncher/10.0.9/modlauncher-10.0.9.jar (missing)
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/net/minecraftforge/mergetool/1.1.5/mergetool-1.1.5-api.jar (missing)
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/com/electronwill/night-config/core/3.6.4/core-3.6.4.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/com/electronwill/night-config/toml/3.6.4/toml-3.6.4.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/apache/maven/maven-artifact/3.8.5/maven-artifact-3.8.5.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/net/jodah/typetools/0.6.3/typetools-0.6.3.jar (missing)
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/jline/jline-reader/3.12.1/jline-reader-3.12.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/jline/jline-terminal/3.12.1/jline-terminal-3.12.1.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/net/minecraftforge/JarJarSelector/0.3.19/JarJarSelector-0.3.19.jar (missing)
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/net/minecraftforge/JarJarMetadata/0.3.19/JarJarMetadata-0.3.19.jar (missing)
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/net/minecraftforge/JarJarFileSystems/0.3.19/JarJarFileSystems-0.3.19.jar (missing)
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/net/minecraftforge/fmlloader/1.20.1-47.2.0/fmlloader-1.20.1-47.2.0.jar (missing)
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/net/minecraftforge/fmlearlydisplay/1.20.1-47.2.0/fmlearlydisplay-1.20.1-47.2.0.jar (missing)
  C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/com/mojang/minecraft/1.20.1/minecraft-1.20.1-client.jar

Native libraries:

Params:
  --username  --version 1.20.1 --gameDir C:/Users/Hamb/AppData/Roaming/PollyMC/instances/Huminar/.minecraft --assetsDir C:/Users/Hamb/AppData/Roaming/PollyMC/assets --assetIndex 5 --uuid  --accessToken  --userType  --versionType release --launchTarget forgeclient --fml.forgeVersion 47.2.0 --fml.mcVersion 1.20.1 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20230612.114412

Window size: 854 x 480

Launcher: standard

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx14080m, -Duser.language=en, -Dminecraft.api.env=custom, -Dminecraft.api.auth.host=https://account.ely.by/api/authlib-injector/authserver, -Dminecraft.api.account.host=https://account.ely.by/api/authlib-injector/api, -Dminecraft.api.session.host=https://account.ely.by/api/authlib-injector/sessionserver, -Dminecraft.api.services.host=https://account.ely.by/api/authlib-injector/minecraftservices, -javaagent:C:/Users/Hamb/AppData/Roaming/PollyMC/libraries/moe/yushi/authlibinjector/1.2.5/authlibinjector-1.2.5.jar=https://account.ely.by/api/authlib-injector, -Dauthlibinjector.yggdrasil.prefetched=eyJtZXRhIjp7InNlcnZlck5hbWUiOiJFbHkuYnkiLCJpbXBsZW1lbnRhdGlvbk5hbWUiOiJBY2NvdW50IEVseS5ieSBhZGFwdGVyIGZvciB0aGUgYXV0aGxpYi1pbmplY3RvciBsaWJyYXJ5IiwiaW1wbGVtZW50YXRpb25WZXJzaW9uIjoiMS4wLjAiLCJmZWF0dXJlLm5vX21vamFuZ19uYW1lc3BhY2UiOnRydWUsImxpbmtzIjp7ImhvbWVwYWdlIjoiaHR0cHM6Ly9lbHkuYnkiLCJyZWdpc3RlciI6Imh0dHBzOi8vYWNjb3VudC5lbHkuYnkvcmVnaXN0ZXIifX0sInNraW5Eb21haW5zIjpbImVseS5ieSIsIi5lbHkuYnkiXSwic2lnbmF0dXJlUHVibGlja2V5IjoiLS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS1cbk1JSUNJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBZzhBTUlJQ0NnS0NBZ0VBeGdGSlJiMGU5ZlJ5Vkc1K0psQ2dcbmgwaGNjUkljZ081eXhFVmtNSmFqQUkxMkV2L1BjN2xwVHQ2T3RLVEVjVU5mallnQm5FaElLYmRMRDBaK0I1QnhcblNnOURRbW96Z3paY2VzU2NwQVNRYjRLdDZQOGl0b3dkYmdiVW00dis2eDFRVUtKamptaEhxOTNtOU9JRWJ4UUxcbkNxK1NyRU1acERyWFJnZDlEaE5Qalp2Lzk1eGltUDhvdHZoNytibUVsOGp3SU5nZkp4MFBBZUpGWWxjZVFjc2hcbmlZaCtMSHRhSXd6YlRUcWtEaWJEbTdRaUVjKy9xR2FiM21BQnRWVHBxdy9yZWZ3Rm9SME04K3hrV0YrMS9EOGtcbkgwV0ZhK3JCaGRqTHlMRysyaGRPcEtYb0gvZk1IMHRRTVBIVTc4SjE3SlZLV3dJV0N3RVdYcDhIaVdTYkl0M2FcbmNtQll0eVczdHFhckZGTU1FQ3gyd21KUDZGVk92WVZUaFp4cTlxYzkvZjN5ZVRHejNnN3pVMVlsakhTVlJQMTZcbmlFYkVuSFFCS3htcmoyY2RaZ29zSmVqNFlwcFY3ZjNpWjhvOFBGNlVZNTFMU3F2YUN0ZVh1V2VZU0pKRVNHQXNcblVvVjdpaEpmV0w4RHltSGFteXdCMkNhaHg3RWlER1MzL2lCY1FVbXBrNFRUZzJGclpQdUtHSXRuMVFmSVJpZU9cbmtubmo5Q1BLaVdkZk90SkJyM2kxRlhMRWZFeGdjSmhRMDBZNkIwOFFWdmdpQ3pVRjN0K1ZBRzNFZjJZSU5ZeUdcbkFYY1cwVElnTWFsd3dnR3pkaFFSaEl0T0RYcHRXaWd5MEROVFVBZ0tRVDlQUzhOMDl5UEJHeElxNjRUOUEzL3pcbkZxQy9rMmJNTFdVU1Z0SWxpbElJdG4wQ0F3RUFBUT09XG4tLS0tLUVORCBQVUJMSUMgS0VZLS0tLS1cbiJ9]

Minecraft process ID: 5624

[authlib-injector] [INFO] Logging file: C:\Users\Hamb\AppData\Roaming\PollyMC\instances\Huminar\.minecraft\authlib-injector.log
[authlib-injector] [INFO] Version: 1.2.5
[authlib-injector] [INFO] Authentication server: https://account.ely.by/api/authlib-injector
[authlib-injector] [INFO] Disabled Mojang namespace
Exception caught from launcher
java.lang.NoClassDefFoundError: cpw/mods/modlauncher/Launcher
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getLibraryDir(IFileDetector.java:55)
	at io.github.zekerzhayard.forgewrapper.installer.detector.MultiMCFileDetector.getLibraryDir(MultiMCFileDetector.java:24)
	at io.github.zekerzhayard.forgewrapper.installer.detector.MultiMCFileDetector.getInstallerJar(MultiMCFileDetector.java:34)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getDataFromInstaller(IFileDetector.java:141)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getInstallProfileExtraData(IFileDetector.java:136)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.checkExtraFiles(IFileDetector.java:170)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:38)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.ClassNotFoundException: cpw.mods.modlauncher.Launcher
	... 10 more
Exiting with ERROR
Process exited with code 2.
Clipboard copy at: 22 Feb 2024 20:35:01 +0200

### Steps to reproduce

Create new instance
Choose version as 1.20.1
Choose loader as forge (I tried latest and suggested versions)
Launch

### Suspected cause

ZekerZhayard ForgeWrapper. It could possibly be fetching the Forge files incorrectly

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by RCencelj** [comment]
You found any workaround for this? Indeed this is an annoying issue at the moment.
