### ISSUE TITLE
Unable to detect forge installer in 1.19.2

### ISSUE THREAD

**Issue by AAK1767** [fn2006/PollyMC#148]
### Version of PollyMC

Pollymc 8.0

### Version of Qt

Qt 6.3.0

### Description of bug

Exception caught from launcher
java.lang.RuntimeException: Unable to detect the forge installer!
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getDataFromInstaller(IFileDetector.java:144)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getInstallProfileExtraData(IFileDetector.java:123)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.checkExtraFiles(IFileDetector.java:157)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:38)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Exiting with ERROR
Process exited with code 2.

### Steps to reproduce

Create a new forge 1.19.2 instance and launch the game

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by max0n4ik** [comment]
same problem

**Comment by evan-goode** [comment]
What version of Forge? This might be fixed upstream: https://github.com/PrismLauncher/PrismLauncher/issues/1934. We could use a merge.

**Comment by max0n4ik** [comment]
> What version of Forge? This might be fixed upstream: [PrismLauncher/PrismLauncher#1934](https://github.com/PrismLauncher/PrismLauncher/issues/1934). We could use a merge.

there is nothing said about version 1.16.5. I tried everything, I do not know what to do now, even just in Minecraft with the usual forge you can not play

**Comment by evan-goode** [comment]
> there is nothing said about version 1.16.5. I tried everything, I do not know what to do now, even just in Minecraft with the usual forge you can not play

There is this comment: https://github.com/PrismLauncher/PrismLauncher/issues/1934#issuecomment-1968075957.

**Comment by max0n4ik** [comment]
i fix this issue 
in the settings, I changed the IP to this one https://meta.prismlauncher.org/v1/

**Comment by SakiGhuleh** [comment]
> i fix this issue in the settings, I changed the IP to this one https://meta.prismlauncher.org/v1/

How do you change the IP? i have the same problem with the same version

**Comment by evan-goode** [comment]
> i fix this issue in the settings, I changed the IP to this one https://meta.prismlauncher.org/v1/

Thanks, looks like Prism fixed the issue this morning: https://github.com/PrismLauncher/meta-launcher/commit/778c197ddf21798fda0ff99b2b1d75d2ed5d848b. I just applied the same manual fix to PollyMC's metadata server, so it should just work now without changing your metadata server to Prism's. You may need to clear your metadata cache (Help -> Clear Metadata Cache) and add and remove Forge on the Minecraft instance.

We use our own metadata server since we want to distribute authlib-injector the same way as all the other components like Forge and Fabric. If you use Prism's metadata server, you won't be able to install authlib-injector as easily. But running our own does cause a bit of a headache in situations like this when manual intervention is required.

> How do you change the IP? i have the same problem with the same version

The option is in Settings -> APIs -> Metadata Server.

**Comment by SakiGhuleh** [comment]
> > i fix this issue in the settings, I changed the IP to this one https://meta.prismlauncher.org/v1/
> 
> Thanks, looks like Prism fixed the issue this morning: [PrismLauncher/meta-launcher@778c197](https://github.com/PrismLauncher/meta-launcher/commit/778c197ddf21798fda0ff99b2b1d75d2ed5d848b). I just applied the same manual fix to PollyMC's metadata server, so it should just work now without changing your metadata server to Prism's. You may need to clear your metadata cache (Help -> Clear Metadata Cache) and add and remove Forge on the Minecraft instance.
> 
> We use our own metadata server since we want to distribute authlib-injector the same way as all the other components like Forge and Fabric. If you use Prism's metadata server, you won't be able to install authlib-injector as easily. But running our own does cause a bit of a headache in situations like this when manual intervention is required.
> 
> > How do you change the IP? i have the same problem with the same version
> 
> The option is in Settings -> APIs -> Metadata Server.

Thanks, both of you! I was worried of not being able to use forge in past versions. Really, the best launcher ever!!

**Comment by AAK1767** [comment]
Can anyone give clear instructions on what to do? My forge version is
43.3.8 and Minecraft version is 1.19.2. Thanks

**Comment by evan-goode** [comment]
> Can anyone give clear instructions on what to do? My forge version is 43.3.8 and Minecraft version is 1.19.2. Thanks

I'm not 100% sure the change I just made fixes this for any version other than 1.16.5, but:

Clear your metadata cache by clicking "Help" on the main window and then selecting "Clear Metadata Cache". Then launch the game as usual.

If that doesn't work, let us know, and you can also try removing Forge from the instance and adding it again. To do that, edit the instance, go to "Version" in the sidebar, find Forge in the list of components, and add it back by clicking "Install Loader" and selecting Forge. The recommended version of Forge (the one with the star) should work, but you can also try the latest version in the list. The recommended version might happen to be the latest in the case of 1.19.2, I'm not sure.

Thank you for helping test this fix! Please let me know what you try and what worked, and if you still get the same error, I have more things you can try.

I don't have PolyMC in front of me at the moment, just going off memory, so sorry if something isn't exact.

**Comment by evan-goode** [comment]
> Thanks, both of you! I was worried of not being able to use forge in past versions. Really, the best launcher ever!!

Prism and Forge deserve all the credit :) As I understand, this one was Mojang's fault: https://github.com/PrismLauncher/PrismLauncher/issues/2170#issuecomment-1969936297

**Comment by Terkyz** [comment]
> > Can anyone give clear instructions on what to do? My forge version is 43.3.8 and Minecraft version is 1.19.2. Thanks
> 
> I'm not 100% sure the change I just made fixes this for any version other than 1.16.5, but:
> 
> Clear your metadata cache by clicking "Help" on the main window and then selecting "Clear Metadata Cache". Then launch the game as usual.
> 
> If that doesn't work, let us know, and you can also try removing Forge from the instance and adding it again. To do that, edit the instance, go to "Version" in the sidebar, find Forge in the list of components, and add it back by clicking "Install Loader" and selecting Forge. The recommended version of Forge (the one with the star) should work, but you can also try the latest version in the list. The recommended version might happen to be the latest in the case of 1.19.2, I'm not sure.
> 
> Thank you for helping test this fix! Please let me know what you try and what worked, and if you still get the same error, I have more things you can try.
> 
> I don't have PollyMC in front of me at the moment, just going off memory, so sorry if something isn't exact.

I can confirm that none of that worked, the same error message keeps appearing.

**Comment by goethegardner** [comment]
I have the same issue and trying the fixes that was said here didn't help. Any help is appreciated.

**Comment by ZsoltiHUB** [comment]
I am also having the same issues with none of the fixes working. :C Please help!

**Comment by Atlas-GND** [comment]
im on 1.20.1 and the steps suggested to fix it didn't work either, the same error keeps going

i tried also downloading forge directly from their website but i couldn't make it to work by manual installing either.

> Exception caught from launcher
> java.lang.RuntimeException: Unable to detect the forge installer!

**Comment by ZsoltiHUB** [comment]
My only temporary fix is having a friend send over the libraries folder from their launcher root folder

**Comment by evan-goode** [comment]
I didn't do something right and the CI overwrote my change. It should be fixed now.

Updated instructions:

1. Close PollyMC
2. Delete the following directories:
  - If you are on Linux:
    - `~/.local/share/PollyMC/assets`
    - `~/.local/share/PollyMC/libraries`
    - `~/.local/share/PollyMC/meta`
    - `~/.local/share/PollyMC/metacache`
  - If you are on Windows:
    - `C:\Users\YOURUSERNAME\AppData\Roaming\PollyMC\assets`
    - `C:\Users\YOURUSERNAME\AppData\Roaming\PollyMC\libraries`
    - `C:\Users\YOURUSERNAME\AppData\Roaming\PollyMC\meta`
    - `C:\Users\YOURUSERNAME\AppData\Roaming\PollyMC\metacache`
  - If you are on macOS:
    - `~/Library/Application Support/PollyMC/assets` 
    -     - `~/Library/Application Support/PollyMC/assets`

**Comment by b00kertie** [comment]
No, it's not working.

**[...]**
Exception caught from launcher
java.lang.RuntimeException: Unable to detect the forge installer!
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getDataFromInstaller(IFileDetector.java:157)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getInstallProfileExtraData(IFileDetector.java:136)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.checkExtraFiles(IFileDetector.java:170)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:38)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Exiting with ERROR
Le processus s'est arrêté avec le code de sortie 2.

**Comment by Terkyz** [comment]
> I didn't do something right and the CI overwrote my change. It should be fixed now.
> 
> Updated instructions:
> 
>     1. Close PollyMC
> 
>     2. Delete the following directories:
> 
> 
>     * If you are on Linux:
>       
>       * `~/.local/share/PollyMC/assets`
>       * `~/.local/share/PollyMC/libraries`
>       * `~/.local/share/PollyMC/meta`
>       * `~/.local/share/PollyMC/metacache`
> 
>     * If you are on Windows:
>       
>       * `C:\Users\YOURUSERNAME\AppData\Roaming\PollyMC\assets`
>       * `C:\Users\YOURUSERNAME\AppData\Roaming\PollyMC\libraries`
>       * `C:\Users\YOURUSERNAME\AppData\Roaming\PollyMC\meta`
>       * `C:\Users\YOURUSERNAME\AppData\Roaming\PollyMC\metacache`
> 
>     * If you are on macOS:
>       
>       * `~/Library/Application Support/PollyMC/assets`
>       * `~/Library/Application Support/PollyMC/libraries`
>       * `~/Library/Application Support/PollyMC/meta`
>       * `~/Library/Application Support/PollyMC/metacache`
> 
> 
>     3. Reopen PollyMC and launch your instance as usual
> 
> 
> Let me know if that works.

Can confirm is working.

For those who have PollyMC installed in Linux as a flatpak, the path you need to go to delete those files/directories is: 
`/home/$USER/.var/app/org.fn2006.PollyMC/data/PollyMC/`

**Comment by evan-goode** [comment]
> No, it's not working.
> 
> **[...]** Exception caught from launcher java.lang.RuntimeException: Unable to detect the forge installer! at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getDataFromInstaller(IFileDetector.java:157) at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getInstallProfileExtraData(IFileDetector.java:136) at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.checkExtraFiles(IFileDetector.java:170) at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:38) at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) Exiting with ERROR Le processus s'est arrêté avec le code de sortie 2.

What operating system are you on? You could try renaming the `PollyMC` directory to `PollyMC.old` or something and relaunching PollyMC in order to regenerate a completely fresh data directory.

You can get your old instances back by deleting the new `PollyMC` directory and renaming `PollyMC.old` back to `PollyMC`.

**Comment by goethegardner** [comment]
> I didn't do something right and the CI overwrote my change. It should be fixed now.
> 
> Updated instructions:
> 
> 1. Close PollyMC
> 2. Delete the following directories:
> 
> * If you are on Linux:
>   
>   * `~/.local/share/PollyMC/assets`
>   * `~/.local/share/PollyMC/libraries`
>   * `~/.local/share/PollyMC/meta`
>   * `~/.local/share/PollyMC/metacache`
> * If you are on Linux but use the Flatpak (thanks @Terkyz):
>   
>   * `~/.var/app/org.fn2006.PollyMC/data/PollyMC/assets`
>   * `~/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries`
>   * `~/.var/app/org.fn2006.PollyMC/data/PollyMC/meta`
>   * `~/.var/app/org.fn2006.PollyMC/data/PollyMC/metacache`
> * If you are on Windows:
>   
>   * `C:\Users\YOURUSERNAME\AppData\Roaming\PollyMC\assets`
>   * `C:\Users\YOURUSERNAME\AppData\Roaming\PollyMC\libraries`
>   * `C:\Users\YOURUSERNAME\AppData\Roaming\PollyMC\meta`
>   * `C:\Users\YOURUSERNAME\AppData\Roaming\PollyMC\metacache`
> * If you are on macOS:
>   
>   * `~/Library/Application Support/PollyMC/assets`
>   * `~/Library/Application Support/PollyMC/libraries`
>   * `~/Library/Application Support/PollyMC/meta`
>   * `~/Library/Application Support/PollyMC/metacache`
> 
> 3. Reopen PollyMC and launch your instance as usual
> 
> Let me know if that works.

It be working boss. Thanks 👍 
btw...



> No, it's not working.
> 
> **[...]** Exception caught from launcher java.lang.RuntimeException: Unable to detect the forge installer! at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getDataFromInstaller(IFileDetector.java:157) at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getInstallProfileExtraData(IFileDetector.java:136) at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.checkExtraFiles(IFileDetector.java:170) at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:38) at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) Exiting with ERROR Le processus s'est arrêté avec le code de sortie 2.

French "people"... Am I right guys?

**Comment by b00kertie** [comment]
> > No, it's not working.
> > **[...]** Exception caught from launcher java.lang.RuntimeException: Unable to detect the forge installer! at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getDataFromInstaller(IFileDetector.java:157) at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getInstallProfileExtraData(IFileDetector.java:136) at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.checkExtraFiles(IFileDetector.java:170) at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:38) at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) Exiting with ERROR Le processus s'est arrêté avec le code de sortie 2.
> 
> What operating system are you on? You could try renaming the `PollyMC` directory to `PollyMC.old` or something and relaunching PollyMC in order to regenerate a completely fresh data directory.
> 
> You can get your old instances back by deleting the new `PollyMC` directory and renaming `PollyMC.old` back to `PollyMC`.

I delete the man directory (no problem for **me**) `rm -r ~/.local/share/PollyMC` now, and then re-executed/installed PollyMC-Linux-x86_64.AppImage. I'm running version 1.19.2 with FORGE 43.3.0, using an offline account. Result : It's working ! Thanks !!
