### ISSUE TITLE
Exception caught from launcher

### ISSUE THREAD

**Issue by koo1140** [fn2006/PollyMC#200]
### Version of PollyMC

PollyMC 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

i dont know, it failed to start

### Steps to reproduce

* installed pollymc
* installed java 17 TLS
* set up java
* got an error when launching world

### Suspected cause

Exception caught from launcher
java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at org.prismlauncher.utils.ReflectionUtils.findMainMethod(ReflectionUtils.java:94)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:86)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Exiting with ERROR
Process exited with code 2.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ItsDragonaire** [comment]
In my experience,
With error code 2, I generally install a version of java from azul or adoptium (zulu & temurin respectively) which it mentions in the error log console, go to edit the instance, click settings, and proceed to enable "skip java compatibility check". This essentially disables the java check layer and forces minecraft to run with the specified java executable path.

**Comment by koo1140** [comment]
Somehow the issue has been resolved.
