### ISSUE TITLE
exited with code 255

### ISSUE THREAD

**Issue by flashballs** [fn2006/PollyMC#206]
### Version of PollyMC

pollymc 8

### Version of Qt

qt 6.3.4

### Description of bug

when i try to run minecraft it crahes and opens a consel that says process exited with error code 255

### Steps to reproduce

download minecraft 1.8.8 click launch button

### Suspected cause

idk but heres the full log the only thing i suspect is maybe im missing a depidincy so a full depidincy list would be nice

PollyMC version: 8.0 (official)

Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [13.107.246.57, 2620:1ec:bdf::57]

textures.minecraft.net resolves to:
    [13.107.246.57, 2620:1ec:bdf::57]

api.mojang.com resolves to:
    [13.107.246.57, 2620:1ec:bdf::57]

Minecraft folder is:
/home/linus/.local/share/PollyMC/instances/1.8.8/.minecraft

Java path is:
/usr/lib/jvm/java-8-openjdk/jre/bin/java

Java is version 1.8.0_432, using 64 (amd64) architecture, from Arch Linux.

Intel(R) Celeron(R) CPU  N3060  @ 1.60GHz
Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Integrated Graphics Controller (rev 35)

DeviceName: VGA compatible controller

Subsystem: Intel Corporation Device 7270

Main Class:
  net.minecraft.client.main.Main

Native path:
  /home/linus/.local/share/PollyMC/instances/1.8.8/natives

Libraries:
  /home/linus/.local/share/PollyMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/linus/.local/share/PollyMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/linus/.local/share/PollyMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /home/linus/.local/share/PollyMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /home/linus/.local/share/PollyMC/libraries/com/mojang/netty/1.8.8/netty-1.8.8.jar
  /home/linus/.local/share/PollyMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /home/linus/.local/share/PollyMC/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar
  /home/linus/.local/share/PollyMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /home/linus/.local/share/PollyMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /home/linus/.local/share/PollyMC/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
  /home/linus/.local/share/PollyMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /home/linus/.local/share/PollyMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /home/linus/.local/share/PollyMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /home/linus/.local/share/PollyMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /home/linus/.local/share/PollyMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /home/linus/.local/share/PollyMC/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar
  /home/linus/.local/share/PollyMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  /home/linus/.local/share/PollyMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  /home/linus/.local/share/PollyMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  /home/linus/.local/share/PollyMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  /home/linus/.local/share/PollyMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  /home/linus/.local/share/PollyMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  /home/linus/.local/share/PollyMC/libraries/com/mojang/realms/1.7.39/realms-1.7.39.jar
  /home/linus/.local/share/PollyMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /home/linus/.local/share/PollyMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /home/linus/.local/share/PollyMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /home/linus/.local/share/PollyMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /home/linus/.local/share/PollyMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9-fixed/log4j-api-2.0-beta9-fixed.jar
  /home/linus/.local/share/PollyMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9-fixed/log4j-core-2.0-beta9-fixed.jar
  /home/linus/.local/share/PollyMC/libraries/tv/twitch/twitch/6.5/twitch-6.5.jar
  /home/linus/.local/share/PollyMC/libraries/com/mojang/minecraft/1.8.8/minecraft-1.8.8-client.jar

Native libraries:
  /home/linus/.local/share/PollyMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
  /home/linus/.local/share/PollyMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar

Params:
  --username  --version 1.8.8 --gameDir /home/linus/.local/share/PollyMC/instances/1.8.8/.minecraft --assetsDir /home/linus/.local/share/PollyMC/assets --assetIndex 1.8 --uuid  --accessToken  --userProperties  --userType 

Window size: 854 x 480

Launcher: standard

Java Arguments:
[-Xms512m, -Xmx3468m, -Duser.language=en]

Minecraft process ID: 2133

[06:46:18] [Client thread/INFO]: Setting user: ZzqMa
[06:46:18] [Client thread/INFO]: (Session ID is token:0:<PROFILE ID>)
[06:46:26] [Client thread/INFO]: LWJGL Version: 2.9.4
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 12/20/24 6:46 AM
Description: Initializing game

java.lang.ExceptionInInitializerError
	at ave.ar(SourceFile:560)
	at ave.am(SourceFile:361)
	at ave.a(SourceFile:310)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.lwjgl.opengl.LinuxDisplay.getAvailableDisplayModes(LinuxDisplay.java:951)
	at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:738)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
	... 7 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at ave.ar(SourceFile:560)
	at ave.am(SourceFile:361)

-- Initialization --
Details:
Stacktrace:
	at ave.a(SourceFile:310)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- System Details --
Details:
	Minecraft Version: 1.8.8
	Operating System: Linux (amd64) version 6.12.6-arch1-1
	Java Version: 1.8.0_432, Arch Linux
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Arch Linux
	Memory: 581241272 bytes (554 MB) / 649592832 bytes (619 MB) up to 3232759808 bytes (3083 MB)
	JVM Flags: 2 total; -Xms512m -Xmx3468m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.8.8
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: No
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /home/linus/.local/share/PollyMC/instances/1.8.8/.minecraft/crash-reports/crash-2024-12-20_06.46.27-client.txt
Process exited with code 255.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by OnlyWeez** [comment]
try install xrand
