### ISSUE TITLE
When press quite the game crahes

### ISSUE THREAD

**Issue by ygames1914A** [fn2006/PollyMC#207]
### Version of PollyMC

8.0
flatpak
Build date: 2023-11-18
Channel: stable

### Version of Qt

5.15.10.

### Description of bug

it crashes when quiting the game using quit button

### Steps to reproduce

PollyMC version: 8.0 (flatpak)

Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [13.107.246.43, 2620:1ec:bdf::43]

textures.minecraft.net resolves to:
    [13.107.246.61, 2620:1ec:bdf::61]

api.mojang.com resolves to:
    [13.107.246.43, 2620:1ec:bdf::43]

Minecraft folder is:
/home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/instances/1.20.1/.minecraft

Java path is:
/app/jdk/17/bin/java

Java is version 17.0.9, using 64 (amd64) architecture, from Flathub.

Intel(R) Core(TM) i3-10100F CPU @ 3.60GHz
NVIDIA Corporation TU116 [GeForce GTX 1660 Ti] (rev a1)

Subsystem: Gigabyte Technology Co., Ltd Device 3fbe

Kernel driver in use: nvidia

OpenGL version string: 4.6.0 NVIDIA 565.77

Main Class:
  net.minecraft.client.main.Main

Native path:
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/instances/1.20.1/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS
traits feature:is_quick_play_singleplayer
traits feature:is_quick_play_multiplayer

Libraries:
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/org/lwjgl/lwjgl-glfw-natives-linux/3.3.2-lwjgl.1/lwjgl-glfw-natives-linux-3.3.2-lwjgl.1.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/org/lwjgl/lwjgl-jemalloc-natives-linux/3.3.1/lwjgl-jemalloc-natives-linux-3.3.1.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/org/lwjgl/lwjgl-natives-linux/3.3.1/lwjgl-natives-linux-3.3.1.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/org/lwjgl/lwjgl-openal-natives-linux/3.3.1/lwjgl-openal-natives-linux-3.3.1.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/org/lwjgl/lwjgl-opengl-natives-linux/3.3.1/lwjgl-opengl-natives-linux-3.3.1.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/org/lwjgl/lwjgl-stb-natives-linux/3.3.1/lwjgl-stb-natives-linux-3.3.1.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/org/lwjgl/lwjgl-tinyfd-natives-linux/3.3.1/lwjgl-tinyfd-natives-linux-3.3.1.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/com/google/code/gson/gson/2.10/gson-2.10.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/com/ibm/icu/icu4j/71.1/icu4j-71.1.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/com/mojang/authlib/4.0.43/authlib-4.0.43.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/com/mojang/brigadier/1.1.8/brigadier-1.1.8.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/io/netty/netty-buffer/4.1.82.Final/netty-buffer-4.1.82.Final.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/io/netty/netty-codec/4.1.82.Final/netty-codec-4.1.82.Final.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/io/netty/netty-common/4.1.82.Final/netty-common-4.1.82.Final.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/io/netty/netty-handler/4.1.82.Final/netty-handler-4.1.82.Final.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/io/netty/netty-resolver/4.1.82.Final/netty-resolver-4.1.82.Final.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/io/netty/netty-transport-classes-epoll/4.1.82.Final/netty-transport-classes-epoll-4.1.82.Final.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/io/netty/netty-transport-native-epoll/4.1.82.Final/netty-transport-native-epoll-4.1.82.Final-linux-aarch_64.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/io/netty/netty-transport-native-epoll/4.1.82.Final/netty-transport-native-epoll-4.1.82.Final-linux-x86_64.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/io/netty/netty-transport-native-unix-common/4.1.82.Final/netty-transport-native-unix-common-4.1.82.Final.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/io/netty/netty-transport/4.1.82.Final/netty-transport-4.1.82.Final.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/it/unimi/dsi/fastutil/8.5.9/fastutil-8.5.9.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/net/java/dev/jna/jna-platform/5.12.1/jna-platform-5.12.1.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/net/java/dev/jna/jna/5.12.1/jna-5.12.1.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/org/slf4j/slf4j-api/2.0.1/slf4j-api-2.0.1.jar
  /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/libraries/com/mojang/minecraft/1.20.1/minecraft-1.20.1-client.jar

Native libraries:

Params:
  --username  --version 1.20.1 --gameDir /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/instances/1.20.1/.minecraft --assetsDir /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/assets --assetIndex 5 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Launcher: standard

Java Arguments:
[-Xms512m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 98

[16:19:00] [Datafixer Bootstrap/INFO]: 188 Datafixer optimizations took 180 milliseconds
[16:19:00] [main/WARN]: Unrecognized user type: offline
[16:19:00] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[16:19:01] [Render thread/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-4.0.43.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:156) ~[authlib-4.0.43.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:55) ~[authlib-4.0.43.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:124) ~[authlib-4.0.43.jar:?]
	at enn.a(SourceFile:733) ~[minecraft-1.20.1-client.jar:?]
	at enn.<init>(SourceFile:442) ~[minecraft-1.20.1-client.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:211) ~[minecraft-1.20.1-client.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:85) ~[authlib-4.0.43.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48) ~[authlib-4.0.43.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:129) ~[authlib-4.0.43.jar:?]
	... 8 more
[16:19:01] [Render thread/INFO]: Setting user: oandygames
[16:19:01] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 build 7
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[16:19:02] [Render thread/INFO]: Reloading ResourceManager: vanilla
[16:19:02] [Worker-Main-6/INFO]: Found unifont_all_no_pua-15.0.06.hex, loading
[16:19:02] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[16:19:03] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[16:19:03] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[16:19:03] [Render thread/INFO]: OpenAL initialized on device Built-in Audio Analog Stereo
[16:19:03] [Render thread/INFO]: Sound engine started
[16:19:03] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[16:19:03] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[16:19:03] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[16:19:03] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[16:19:03] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[16:19:03] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[16:19:03] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[16:19:03] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[16:19:03] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[16:19:04] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[16:19:04] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[16:19:04] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[16:19:04] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[16:19:17] [Render thread/INFO]: Connecting to 127.0.0.1, 25565
[16:19:17] [Render thread/WARN]: Unknown custom packed identifier: minecraft:register
[16:19:18] [Render thread/INFO]: [System] [CHAT] oandygames joined the game
[16:19:18] [Render thread/INFO]: Loaded 2 advancements
[16:20:10] [Render thread/INFO]: Stopping!
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0x7) at pc=0x00007efde145133c, pid=98, tid=99
#
# JRE version: OpenJDK Runtime Environment 21.9 (17.0.9+7) (build 17.0.9+7)
# Java VM: OpenJDK 64-Bit Server VM 21.9 (17.0.9+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libnvidia-glcore.so.565.77+0xa5133c]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/instances/1.20.1/.minecraft/core.98)
#
# An error report file with more information is saved as:
# /home/oandygames/.var/app/org.fn2006.PollyMC/data/PollyMC/instances/1.20.1/.minecraft/hs_err_pid98.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Process crashed with exitcode 6.
test

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by RageGen** [comment]
Same in PrismLauncher
I am not found a solution, too

**Comment by RageGen** [comment]
@ygames1914A __GL_THREADED_OPTIMIZATIONS=0 in environment variables solved my problem

**Comment by ygames1914A** [comment]
> __GL_THREADED_OPTIMIZATIONS

@RageGen Thanks it worked
