### ISSUE TITLE
java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker

### ISSUE THREAD

**Issue by YusufSuleman** [fn2006/PollyMC#53]
### Operating System

Linux

### Version of PollyMC

PollyMC 6.1

### Version of Qt

Qt 6.2.4

### Description of bug

I tried making my own modpack, when I was downloading, my OCD came and I doubted, if I already installed, the mod and did it again, then I accidently used Modrinth instead of Curseforge once. I checked my list of mods and found that there was a memory_repo folder and deleted the second version of IndustrialCraft in it. After finishing, I got this in the log
```
[15:48:19] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_352]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_352]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_352]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_352]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_352]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_352]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_352]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_352]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
Exception caught from launcher
net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
	at java.lang.Runtime.exit(Runtime.java:101)
	at java.lang.System.exit(System.java:987)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
[15:48:19] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[15:48:19] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[15:48:19] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
Exiting with ERROR
Exception in thread "main" 
[15:48:19] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:101)
[15:48:19] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:987)
[15:48:19] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:76)
Process exited with code 1.
```
Here is the lists of mods:
![image](https://user-images.githubusercontent.com/63107868/218075218-259761c6-4c64-45ce-9b12-68c43c9dc58b.png)
Even removing the memory_repo folder before taking the screenshot, didn't fix or give a new error

### Steps to reproduce

Download the same mods from Curseforge (inside the launcher), Try installing a mod, twice or not as I didn't see duplicates except for IndustrialCraft.

### Suspected cause

Multiple mods conflicting or Java being weird, I am using` /usr/lib/jvm/java-8-openjdk/bin/java`

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by fn2006** [comment]
It looks like you need to install SpongeMixins.
This is an issue with your modlist, not the launcher though.
