### ISSUE TITLE
(KDE) GLFW error 65548: Wayland: The platform does not support setting the window icon

### ISSUE THREAD

**Issue by milkknife** [fn2006/PollyMC#99]
### Operating System

Linux

### Version of PollyMC

PollyMC 7.2

### Version of Qt

Qt 5.15.10

### Description of bug

Crashes when launching minecraft.
```
Minecraft
GLFW error 65548: Wayland: The platform does not support setting the window icon.
Please make sure you have up-to-date drivers (see aka.ms/mcdriver for instructions).
press enter to continue [16:37:01] [Render thread/WARN]: Failed to create window: 
net.minecraft.class_1041$class_4716: GLFW error 65548: Wayland: The platform does not support setting the window icon
	at net.minecraft.class_1041.method_4501(class_1041.java:223) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokePPV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.nglfwSetWindowIcon(GLFW.java:2336) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwSetWindowIcon(GLFW.java:2368) ~[lwjgl-glfw-3.3.1.jar:?]
	at net.minecraft.class_1041.method_4491(class_1041.java:185) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:494) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:205) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.12.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
```

### Steps to reproduce

run the game on KDE Plasma 5.27.7

### Suspected cause

The game works fine on Hyprland or any wlroots compositor, but crashes on KDE. The error mentions 'window icon' which is what KDE sets. It's a KDE+wayland issue but most wayland programs on it run anyway and just set the yellow W (wayland logo) for these applications. I was wondering if there's a way to prevent it from setting an icon, as a stopgap.

Another way to look at it, the window icon is so important it escalates uncaught up the whole stack, so it could also be an error handling issue.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by XandrCopyrighted** [comment]
same issue on my sway vm

**Comment by felifluid** [comment]
Facing the same issue on kde plasma with the prismlauncher.

**Comment by danielwerg** [comment]
Try `XDG_SESSION_TYPE=x11` env
